### ISSUE TITLE
Enable footnotes to work with multiple fields i.e. Article.body and Article.description

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-tng#150]
No good deed goes unpunished.  Of course somebody would want to put footnotes into the first paragraph of an article.

At least the following pages contain footnotes in the description field (first paragraph) that are not working in the public UI.
- John Aiso

### Acceptance criteria
- Affected pages show footnotes in the description i.e. first paragraph
- ...and also in quote blocks

**Comment by gjost** [comment]
And they also want to put footnotes in quote blocks:
- John Aiso

**Comment by gjost** [comment]
Fixed in 53ebcb3, `150-footnotes` branch merged into develop in 62d7086. Code pushed to `encycstage`, database is being recreated.

**Comment by CamJohns** [comment]
Using John Aiso's article as the test location, I still see the ref tags in both the description and the quote block.

**Comment by CamJohns** [comment]
Using Aiso as an example, as well as a couple of other articles with references in first paragraph, this is fixed for both criteria points.
