### ISSUE TITLE
Layout of site logo is wonky

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-tng#55]
Screenshot was taken in Firefox

![Image](https://github.com/user-attachments/assets/78962065-9ecd-4552-a5b5-a553e9cb4a72)

**Comment by nicklee** [comment]
I've fixed this as part of: https://github.com/denshoproject/encyc-tng/pull/59

**Comment by gjost** [comment]
Unfortunately I'm still seeing this in my dev and staging environments

**Comment by nicklee** [comment]
How strange, it's working locally but I can see the css isn't correct on staging:

http://localhost:8082/pattern-library/render-pattern/patterns/pages/collections/collections--authors.html

We ended up moving away from the utility class setup and instead hardcoded a rem value for this font size, as it was quite bespoke based on the breakpoint.

![Image](https://github.com/user-attachments/assets/005d704a-3405-4a69-8fa2-15a879c9301d)

**Comment by gjost** [comment]
TBX resolved this for us
