### ISSUE TITLE
Article citations

### ISSUE THREAD

**Issue by gjost** [denshoproject/encyc-tng#96]
Current Encyclopedia articles all have a "Cite" link that presents example citations of the article in various formats.

Acceptance criteria
- Articles have a Cite link
- that pops up a window containing citations 
- in various formats
- that are not borken

**Comment by gjost** [comment]
Mostly fixed as of commit `b3670ef` on the `develop` branch.

Templates for each citation style are moved out of the code into `templates/encyclopedia/citations/`.
Citations are not perfectly formatted yet but they're basically working.

**Comment by CamJohns** [comment]
-Citation button works on sample of test articles
	-Problem: For each citation style , the copy-paste field still shows HTML 
                            attributes in citation links
		Sample of example articles where issue persists :
https://encycstage.densho.org/tolan-committee/
https://encycstage.densho.org/takuichi-fujii/
https://encycstage.densho.org/records-about-japanese-americans-relocated-during-world-war-ii/

**Comment by gjost** [comment]
The actual citation templates are in `/encyctng/encyclopedia/templates/encyclopedia/citations/`.
Links to these citation templates appear in this component template: `/encyctng/styleguide/templates/patterns/components/modal/modal_cite.html`

**Comment by gjost** [comment]
Fixed(?) in `096-citations` branch commit aca9345, merged into `develop` in 8bef677 and pushed to stage.
